app_sicpej/administracion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='root_login'),
    # ------------ ------------- -----------------
    path('administracion/', include('apps_sicpej.administracion.urls')),
    path('gestion/', include('apps_sicpej.gestion.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_sicpej/apps_sicpej/administracion/urls.py
from django.urls import path

from .views import (
    ArchivoRegionalListView, ArchivoRegionalCreateView, ArchivoRegionalUpdateView,
    JuzgadoListView, JuzgadoCreateView, JuzgadoUpdateView
)

from .views_files.instancia_views import InstanciaListView,InstanciaCreateView,InstanciaUpdateView
from .views_files.materia_views import MateriaListView,MateriaCreateView,MateriaUpdateView,MateriaDetailView
from .views_files.tipojuicio_views import TipoJuicioListView,TipoJuicioCreateView,TipoJuicioUpdateView,TipoJuicioDetailView
from .views_files.distritojudicial_views import DistritoJudicialListView,DistritoJudicialCreateView,DistritoJudicialUpdateView,DistritoJudicialDetailView
from .views_files.tipojuzgado_views import TipoJuzgadoListView,TipoJuzgadoCreateView,TipoJuzgadoUpdateView,TipoJuzgadoDetailView
from .views_files.usuario_configuracion_views import (
    UserListView, UserCreateView, 
    UserUpdateView, UserDetailView, 
    UserDeleteView
)
from .views_files.regionjudicial_views import RegionJudicialListView,RegionJudicialCreateView,RegionJudicialUpdateView,RegionJudicialDetailView 
from .views_files.organojurisdiccional_views import OrganoJurisdiccionalListView,OrganoJurisdiccionalCreateView,OrganoJurisdiccionalUpdateView 
from .views_files.estadisticas_view import EstadisticasDashboardView

app_name = 'administracion'

urlpatterns = [
    # Archivos Regionales
    path('archivos-regional/', ArchivoRegionalListView.as_view(), name='lista_archivos_regional'),
    path('archivos-regional/nuevo/', ArchivoRegionalCreateView.as_view(), name='nuevo_archivo_regional'),
    path('archivos-regional/editar/<int:pk>/', ArchivoRegionalUpdateView.as_view(), name='editar_archivo_regional'),
    
    # Juzgados
    path('juzgados/', JuzgadoListView.as_view(), name='lista_juzgados'),
    path('juzgados/nuevo/', JuzgadoCreateView.as_view(), name='nuevo_juzgado'),
    path('juzgados/editar/<int:pk>/', JuzgadoUpdateView.as_view(), name='editar_juzgado'),

    # Instancias
    path('instancias/', InstanciaListView.as_view(), name='lista_instancias'),
    path('instancias/nueva/', InstanciaCreateView.as_view(), name='nueva_instancia'),
    path('instancias/editar/<int:pk>/', InstanciaUpdateView.as_view(), name='editar_instancia'),

    # Materia
    path('materias/', MateriaListView.as_view(), name='lista_materias'),
    path('materias/nueva/', MateriaCreateView.as_view(), name='nueva_materia'),
    path('materias/editar/<int:pk>/', MateriaUpdateView.as_view(), name='editar_materia'),
    path('materias/ver/<int:pk>/', MateriaDetailView.as_view(), name='ver_materia'),

    # Juicios
    path('tipos-juicio/', TipoJuicioListView.as_view(), name='lista_tipos_juicio'),
    path('tipos-juicio/nuevo/', TipoJuicioCreateView.as_view(), name='nuevo_tipo_juicio'),
    path('tipos-juicio/editar/<int:pk>/', TipoJuicioUpdateView.as_view(), name='editar_tipo_juicio'),
    path('tipos-juicio/ver/<int:pk>/', TipoJuicioDetailView.as_view(), name='ver_tipo_juicio'),

    # Distrito Judicial
    path('distritos-judiciales/', DistritoJudicialListView.as_view(), name='lista_distritos'),
    path('distritos-judiciales/nuevo/', DistritoJudicialCreateView.as_view(), name='nuevo_distrito'),
    path('distritos-judiciales/editar/<int:pk>/', DistritoJudicialUpdateView.as_view(), name='editar_distrito'),
    path('distritos-judiciales/ver/<int:pk>/', DistritoJudicialDetailView.as_view(), name='ver_distrito'),

    # Tipo juzgado
    #path('tipos-juzgado/', TipoJuzgadoListView.as_view(), name='lista_tipos_juzgado'),
    #path('tipos-juzgado/nuevo/', TipoJuzgadoCreateView.as_view(), name='nuevo_tipo_juzgado'),
    #path('tipos-juzgado/editar/<int:pk>/', TipoJuzgadoUpdateView.as_view(), name='editar_tipo_juzgado'),
    #path('tipos-juzgado/ver/<int:pk>/', TipoJuzgadoDetailView.as_view(), name='ver_tipo_juzgado'),
    #path('tipos-juzgado/eliminar/<int:pk>/', TipoJuzgadoDeleteView.as_view(), name='eliminar_tipo_juzgado'),

    # Region judicial
    path('regiones-judiciales/', RegionJudicialListView.as_view(), name='lista_regiones'),
    path('regiones-judiciales/nuevo/', RegionJudicialCreateView.as_view(), name='nueva_region'),
    path('regiones-judiciales/editar/<int:pk>/', RegionJudicialUpdateView.as_view(), name='editar_region'),
    path('regiones-judiciales/ver/<int:pk>/', RegionJudicialDetailView.as_view(), name='ver_region'),

    # Organo juridiccial
    path('organo-juridiccial/', OrganoJurisdiccionalListView.as_view(), name='lista_organosjurisdiccionales'),
    path('organo-juridiccial/nuevo/', OrganoJurisdiccionalCreateView.as_view(), name='nuevo_organojurisdiccional'),
    path('organo-juridiccial/editar/<int:pk>/', OrganoJurisdiccionalUpdateView.as_view(), name='editar_organojurisdiccional'),

    path('estadisticas/', EstadisticasDashboardView.as_view(), name='dashboard_estadisticas'),

    #Usuarios
    path('usuarios/', UserListView.as_view(), name='lista_usuarios'),
    path('usuario/nuevo/', UserCreateView.as_view(), name='nuevo_usuario'),
    path('usuario/<int:pk>/', UserDetailView.as_view(), name='ver_usuario'),
    path('usuario/<int:pk>/editar/', UserUpdateView.as_view(), name='editar_usuario'),
    path('usuario/<int:pk>/eliminar/', UserDeleteView.as_view(), name='eliminar_usuario'),

]

app_sicpej/apps_sicpej/gestion/urls.py
from django.urls import path
from .views_files.paquete_views import * 
from .views_files.expediente_views import * 
from .views_files.pdf_views import *
from .views_files.api_views import *
#PaqueteListView,PaqueteCreateView, PaqueteUpdateView,PaqueteDetailView,PaqueteDeleteView, AsignarPaquetePerfilView
from .views_files.tipo_cuadernillo_views import *
from .views_files.perfiles_views import *
from .views_files.usuario_perfil_views import *

app_name = 'gestion'

urlpatterns = [
    # Gestión de paquetes
    #path('paquetes/nuevo/', PaqueteCreateView.as_view(), name='nuevo_paquete'),
    # PaqueteCreateMultipleView
    path('paquetes/nuevo/', PaqueteCreateMultipleView.as_view(), name='nuevo_paquete'),
    path('paquete/<int:paquete_id>/crear-extension-paquete/', CrearExtensionPaqueteAutoView.as_view(), name='crear_extension_paquete'),
    path('paquetes/nuevo/admin/', PaqueteCreateViewAdmin.as_view(), name='nuevo_paquete_admin'),

    # Paquetes
    #path('paquetes/', PaqueteListView.as_view(), name='lista_paquetes'),
    path('paquetes/editar/<int:pk>/', PaqueteUpdateView.as_view(), name='editar_paquete'),
    path('paquetes/ver/<int:pk>/detalle', PaqueteDetailView.as_view(), name='ver_paquete'),
    path('paquetes/eliminar/<int:pk>/', PaqueteDeleteView.as_view(), name='eliminar_paquete'),
    path('paquetes/lista/', PaqueteListView.as_view(), name='lista_paquetes'),
    path('paquetes/asignar/', AsignarPaquetePerfilView.as_view(), name='asignar_paquetes'),


    path('perfiles/', PerfilListView.as_view(), name='lista_perfiles'),
    path('perfiles/nuevo/', PerfilCreateView.as_view(), name='nuevo_perfil'),
    path('perfiles/<int:pk>/editar/', PerfilUpdateView.as_view(), name='editar_perfil'),
    path('usuarios-perfiles/', UsuarioPerfilListView.as_view(), name='lista_usuariosperfiles'),
    path('usuarios-perfiles/nuevo/', UsuarioPerfilCreateView.as_view(), name='nuevo_usuarioperfil'),
    path('usuarios-perfiles/<int:pk>/editar/', UsuarioPerfilUpdateView.as_view(), name='editar_usuarioperfil'),
    path('paquetes/asignados/', PaquetesAsignadosUsuarioView.as_view(), name='paquetes_asignados'),
    
    # Selección inicial
    #Solo admin
    path('paquetes/seleccion/', SeleccionArchivoRegionalView.as_view(), name='seleccion_archivo'),
    #Capturista
    path('paquetes/seleccion-juzgado/<int:archivo_id>/', SeleccionJuzgadoView.as_view(), name='seleccion_juzgado'),
    path('paquetes/organo-jurisdiccional/<int:archivo_id>/', SeleccionOrganoJurisdiccionalView.as_view(), name='seleccion_organo_jurisdiccional'),
    
    #path('paquetes/editar/<int:pk>/', PaqueteUpdateView.as_view(), name='editar_paquete'),
    # Cambiar selección
    path('paquetes/cambiar-seleccion/', CambiarSeleccionView.as_view(), name='cambiar_seleccion'),

    # ################################################################################################################

    # Tipos de cuadernillos
    path('tipo-cuadernillos/', TipoCuadernilloListView.as_view(), name='lista_tipo_cuadernillos'),
    path('tipo-cuadernillos/nuevo/', TipoCuadernilloCreateView.as_view(), name='nuevo_tipo_cuadernillo'),
    path('tipo-cuadernillos/<int:pk>/editar/', TipoCuadernilloUpdateView.as_view(), name='editar_tipo_cuadernillo'),
    path('tipo-cuadernillos/<int:pk>/', TipoCuadernilloDetailView.as_view(), name='detalle_tipo_cuadernillo'),

    path('expediente/paquete/<int:paquete_id>/registrar-expediente/', CrearExpedienteRedireccionView.as_view(), name='nuevo_expediente_rapido'),
    path('expediente/paquete/<int:paquete_id>/nuevo/', ExpedienteCreateView.as_view(), name='nuevo_expediente'),
    path('expediente/<int:pk>/editar/', ExpedienteUpdateView.as_view(), name='editar_expediente'),
    path('expediente/<int:pk>/', ExpedienteDetailView.as_view(), name='detalle_expediente'),
    path('expedientes/', ExpedienteListView.as_view(), name='lista_expedientes'),
    path('expedientes/<int:organo_id>/', ExpedienteListView.as_view(), name='lista_expedientes_por_organo'),
    path('expedientes/mover/paquete', MoverExpedientesAPaqueteView.as_view(), name='mover_expedientes_paquete'),

    # ################################################################################################################

    #reporte pdf
    path('paquete/<int:paquete_id>/pdf/', generar_pdf_paquete, name='generar_pdf_paquete'),
    
    # API endpoints
    path('api/juzgados/', juzgados_por_materia, name='api_juzgados_por_materia'),
    path('api/organos-jurisdiccionales/', organojurisdiccional_por_materia, name='api_organos_jurisdiccionales_por_materia'),
    #   lista_organos_jurisdiccionales
    path('api/organos-jurisdiccionales-general/', lista_organos_jurisdiccionales, name='api_lista_organos_jurisdiccionales'),
    path('api/tipos-cuadernillos/', lista_tipos_cuadernillos, name='api_lista_tipos_cuadernillos'),
    path('api/nombre-usuario-perfiles/', nombre_usuario_perfil, name='api_nombre_usuario_perfil'),
    path('api/paquete/cambiar-estatus/', cambiar_estatus_paquete, name='cambiar_estatus_paquete'),
    path('api/validar-expediente-tomo/', validar_expediente_tomo, name='api_validar_expediente_tomo'),
    path('api/expedientes/<int:pk>/detalle', ExpedienteDetailAPIView.as_view(), name='expediente-detalle'),
    path('api/expedientes/detalle/', ExpedienteDetailPostAPIView.as_view(), name='expediente-detalle-post'),

    
    # Cuadernillo endpoints
    path('cuadernillos/expediente/<int:expediente_id>/', cuadernillos_por_expediente, name='cuadernillos_por_expediente'),
    path('cuadernillo/create/', create_cuadernillo,name='crear_cuadernillo'),
    path('cuadernillo/update/<int:pk>/', update_cuadernillo,name='modificar_cuadernillo'),
    path('cuadernillo/delete/<int:pk>/', delete_cuadernillo,name='eliminar_cuadernillo'),

    # Acumulado
    path('acumulado/expediente/<int:expediente_id>/', acumulado_por_expediente, name='acumulados_por_expediente'),
    path('acumulado/create/', create_acumulado, name='crear_acumulado'),
    path('acumulado/update/<int:pk>/', update_acumulado,name='modificar_acumulado'),
    path('acumulado/delete/<int:pk>/', delete_acumulado,name='eliminar_acumulado'),

    # Avocamiento
    path('avocamiento/expediente/<int:expediente_id>/', avocamientos_por_expediente, name='avocamientos_por_expediente'),
    path('avocamiento/create/', create_avocamiento),
    path('avocamiento/update/<int:pk>/', update_avocamiento),
    path('avocamiento/delete/<int:pk>/', delete_avocamiento),
]

app_sicpej/templates/sicpej/sidebar.html
{% load static %}
<style>
  .img-tribunal {
    position: absolute;
    left: 50%;
    bottom: 4%;
    transform: translateX(-50%);
    opacity: 0.6;
  }
</style>

<aside id="layout-menu" class="layout-menu menu-vertical menu" data-bs-theme="dark">
    <img src="{% static "assets_sicpej/img/android-chrome-192x192.png" %}" alt="" width="150" height="150" class="img-tribunal">
    <div class="app-brand demo">
      <a href="index.html" class="app-brand-link">
        
        <span class="app-brand-text demo menu-text fw-semibold ms-2">SICPEJ TSJ</span>
      </a>

      <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path
            d="M8.47365 11.7183C8.11707 12.0749 8.11707 12.6531 8.47365 13.0097L12.071 16.607C12.4615 16.9975 12.4615 17.6305 12.071 18.021C11.6805 18.4115 11.0475 18.4115 10.657 18.021L5.83009 13.1941C5.37164 12.7356 5.37164 11.9924 5.83009 11.5339L10.657 6.707C11.0475 6.31653 11.6805 6.31653 12.071 6.707C12.4615 7.09747 12.4615 7.73053 12.071 8.121L8.47365 11.7183Z"
            fill-opacity="0.9" />
          <path
            d="M14.3584 11.8336C14.0654 12.1266 14.0654 12.6014 14.3584 12.8944L18.071 16.607C18.4615 16.9975 18.4615 17.6305 18.071 18.021C17.6805 18.4115 17.0475 18.4115 16.657 18.021L11.6819 13.0459C11.3053 12.6693 11.3053 12.0587 11.6819 11.6821L16.657 6.707C17.0475 6.31653 17.6805 6.31653 18.071 6.707C18.4615 7.09747 18.4615 7.73053 18.071 8.121L14.3584 11.8336Z"
            fill-opacity="0.4" />
        </svg>
      </a>
    </div>

    <div class="menu-inner-shadow"></div>

    <ul class="menu-inner py-1">
      <!-- Dashboards -->
      <li class="menu-item open">
        <a href="{% url 'administracion:dashboard_estadisticas' %}" class="menu-link">
          <i class="menu-icon icon-base ri ri-home-smile-line"></i>
          <div data-i18n="Dashboard">Dashboard</div>
        </a>
      </li>

      {% if user.configuracion.es_administrador_general %}
        <li class="menu-header small mt-5">
          <span class="menu-header-text" data-i18n="Administración">Administración</span>
        </li>
        {% with request.resolver_match.url_name as current_view %}
        <li class="menu-item {% if current_view == 'lista_archivos_regional' or current_view == 'lista_juzgados' or current_view == 'lista_instancias' or current_view == 'lista_materias' or current_view == 'lista_tipos_juicio' or current_view == 'lista_distritos' %} active open {% endif %}">
          <a href="javascript:void(0);" class="menu-link menu-toggle">
            <i class="menu-icon icon-base ri ri-folder-2-line"></i>
            <div data-i18n="Catálogos"> Catálogos</div>
          </a>
          <ul class="menu-sub">
            <li class="menu-item {% if request.resolver_match.url_name == 'lista_archivos_regional' %}active{% endif %}">
              <a href="{% url 'administracion:lista_archivos_regional' %}" class="menu-link">
                <div data-i18n="Archivo regional">Archivo regional</div>
              </a>
            </li>
            <li class="menu-item {% if request.resolver_match.url_name == 'lista_juzgados' %}active{% endif %}" style="display:none;">
                <a href="{% url 'administracion:lista_juzgados' %}" class="menu-link">
                  <div data-i18n="Juzgados">Juzgados</div>
                </a>
            </li>
            <li class="menu-item {% if request.resolver_match.url_name == 'lista_instancias' %}active{% endif %}">
              <a href="{% url 'administracion:lista_instancias' %}" class="menu-link">
                <div data-i18n="Instancias">Instancias</div>
              </a>
            </li>
            <li class="menu-item {% if request.resolver_match.url_name == 'lista_materias' %}active{% endif %}">
              <a href="{% url 'administracion:lista_materias' %}" class="menu-link">
                <div data-i18n="Materias">Materias</div>
              </a>
            </li>
            <li class="menu-item {% if request.resolver_match.url_name == 'lista_distritos' %}active{% endif %}">
              <a href="{% url 'administracion:lista_distritos' %}" class="menu-link">
                <div data-i18n="Distritos judiciales">Distritos judiciales</div>
              </a>
            </li>
            <li class="menu-item {% if request.resolver_match.url_name == 'lista_regiones' %}active{% endif %}">
              <a href="{% url 'administracion:lista_regiones' %}" class="menu-link">
                <div data-i18n="Regiones judiciales">Regiones judiciales</div>
              </a>
            </li>
            <li class="menu-item {% if request.resolver_match.url_name == 'lista_organosjuridiccionales' %}active{% endif %}">
              <a href="{% url 'administracion:lista_organosjurisdiccionales' %}" class="menu-link">
                <div data-i18n="Organos jurisdiccionales">Organos jurisdiccionales</div>
              </a>
            </li>
            <li class="menu-item {% if request.resolver_match.url_name == 'lista_perfiles' %}active{% endif %}">
              <a href="{% url 'gestion:lista_perfiles' %}" class="menu-link">
                <div data-i18n="Perfiles">Perfiles</div>
              </a>
            </li>
          </ul>
        </li>
        {% endwith %}
      {% endif %}

      {% if not user.configuracion.es_usuario_consulta %}
      <li class="menu-header small mt-5">
        <span class="menu-header-text" data-i18n="Expedientes">Expedientes</span>
      </li>
      <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle">
          <i class="menu-icon icon-base ri ri-folder-2-line"></i>
          <div data-i18n="Gestión">Gestión</div>
        </a>
        <ul class="menu-sub">
          {% if user.configuracion.es_administrador_general %}
          <li class="menu-item">
            <a href="{% url 'gestion:lista_paquetes' %}" class="menu-link">
              <div data-i18n="Paquetes">Paquetes</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'gestion:lista_expedientes' %}" class="menu-link">
              <div data-i18n="Expedientes">Expedientes</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'gestion:lista_usuariosperfiles' %}" class="menu-link">
              <div data-i18n="Capturistas">Capturistas</div>
            </a>
          </li>
          {% endif %}

          {% if user.configuracion.es_administrador_regional %}
          <li class="menu-item">
            <a href="{% url 'gestion:lista_paquetes' %}" class="menu-link">
              <div data-i18n="Paquetes">Paquetes</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'gestion:lista_expedientes' %}" class="menu-link">
              <div data-i18n="Expedientes">Expedientes</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'gestion:lista_usuariosperfiles' %}" class="menu-link">
              <div data-i18n="Capturistas">Capturistas</div>
            </a>
          </li>
          {% endif %}

          {% if user.configuracion.es_capturista_regional%}
          <li class="menu-item">
            <a href="{% url 'gestion:lista_paquetes' %}" class="menu-link">
              <div data-i18n="Paquetes">Paquetes</div>
            </a>
          </li>
          {% endif %}
        </ul>
      </li>
      {% endif %}

      <li class="menu-header small mt-5">
        <span class="menu-header-text" data-i18n="Consultas">Consultas</span>
      </li>

      <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle">
          <i class="menu-icon icon-base ri ri-file-search-line"></i>
          <div data-i18n="Consultas">Consultas</div>
        </a>
        <ul class="menu-sub">
          {% if user.configuracion.es_usuario_consulta or user.configuracion.es_administrador_general%}
          <li class="menu-item">
            <a href="{% url 'gestion:lista_paquetes' %}" class="menu-link">
              <div data-i18n="Paquetes">Paquetes</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'gestion:lista_expedientes' %}" class="menu-link">
              <div data-i18n="Expedientes">Expedientes</div>
            </a>
          </li>
          {% endif %}
        </ul>
      </li>


      {% if user.configuracion.es_administrador_general %}
      <li class="menu-header small mt-5">
        <span class="menu-header-text" data-i18n="Usuarios">Usuarios</span>
      </li>
      <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle">
          <i class="menu-icon icon-base ri ri-user-line"></i>
          <div data-i18n="Usuarios">Usuarios</div>
        </a>
        <ul class="menu-sub">
          <li class="menu-item">
            <a href="{% url 'administracion:lista_usuarios' %}" class="menu-link">
              <div data-i18n="Listado">Listado</div>
            </a>
          </li>
          <li class="menu-item">
            <a href="{% url 'administracion:nuevo_usuario' %}" class="menu-link">
              <div data-i18n="Nuevo">Nuevo</div>
            </a>
          </li>
        </ul>
      </li>
      {% endif %}
         
    </ul>
  </aside>

<div class="menu-mobile-toggler d-xl-none rounded-1">
<a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large text-bg-secondary p-2 rounded-1">
    <i class="ri ri-menu-line icon-base"></i>
    <i class="ri ri-arrow-right-s-line icon-base"></i>
</a>
</div>
<!-- / Menu -->