app_sicpej/administracion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('login/', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='root_login'),
    # ------------ ------------- -----------------
    path('administracion/', include('apps_sicpej.administracion.urls')),
    path('gestion/', include('apps_sicpej.gestion.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_sicpej/apps_sicpej/administracion/urls.py
from django.urls import path

from .views import (
    ArchivoRegionalListView, ArchivoRegionalCreateView, ArchivoRegionalUpdateView,
    JuzgadoListView, JuzgadoCreateView, JuzgadoUpdateView
)

from .views_files.instancia_views import InstanciaListView,InstanciaCreateView,InstanciaUpdateView
from .views_files.materia_views import MateriaListView,MateriaCreateView,MateriaUpdateView,MateriaDetailView
from .views_files.tipojuicio_views import TipoJuicioListView,TipoJuicioCreateView,TipoJuicioUpdateView,TipoJuicioDetailView
from .views_files.distritojudicial_views import DistritoJudicialListView,DistritoJudicialCreateView,DistritoJudicialUpdateView,DistritoJudicialDetailView
from .views_files.tipojuzgado_views import TipoJuzgadoListView,TipoJuzgadoCreateView,TipoJuzgadoUpdateView,TipoJuzgadoDetailView
from .views_files.usuario_configuracion_views import (
    UserListView, UserCreateView, 
    UserUpdateView, UserDetailView, 
    UserDeleteView
)
from .views_files.regionjudicial_views import RegionJudicialListView,RegionJudicialCreateView,RegionJudicialUpdateView,RegionJudicialDetailView 
from .views_files.organojurisdiccional_views import OrganoJurisdiccionalListView,OrganoJurisdiccionalCreateView,OrganoJurisdiccionalUpdateView 
from .views_files.estadisticas_view import EstadisticasDashboardView

app_name = 'administracion'

urlpatterns = [
    # Archivos Regionales
    path('archivos-regional/', ArchivoRegionalListView.as_view(), name='lista_archivos_regional'),
    path('archivos-regional/nuevo/', ArchivoRegionalCreateView.as_view(), name='nuevo_archivo_regional'),
    path('archivos-regional/editar/<int:pk>/', ArchivoRegionalUpdateView.as_view(), name='editar_archivo_regional'),
    
    # Juzgados
    path('juzgados/', JuzgadoListView.as_view(), name='lista_juzgados'),
    path('juzgados/nuevo/', JuzgadoCreateView.as_view(), name='nuevo_juzgado'),
    path('juzgados/editar/<int:pk>/', JuzgadoUpdateView.as_view(), name='editar_juzgado'),

    # Instancias
    path('instancias/', InstanciaListView.as_view(), name='lista_instancias'),
    path('instancias/nueva/', InstanciaCreateView.as_view(), name='nueva_instancia'),
    path('instancias/editar/<int:pk>/', InstanciaUpdateView.as_view(), name='editar_instancia'),

    # Materia
    path('materias/', MateriaListView.as_view(), name='lista_materias'),
    path('materias/nueva/', MateriaCreateView.as_view(), name='nueva_materia'),
    path('materias/editar/<int:pk>/', MateriaUpdateView.as_view(), name='editar_materia'),
    path('materias/ver/<int:pk>/', MateriaDetailView.as_view(), name='ver_materia'),

    # Juicios
    path('tipos-juicio/', TipoJuicioListView.as_view(), name='lista_tipos_juicio'),
    path('tipos-juicio/nuevo/', TipoJuicioCreateView.as_view(), name='nuevo_tipo_juicio'),
    path('tipos-juicio/editar/<int:pk>/', TipoJuicioUpdateView.as_view(), name='editar_tipo_juicio'),
    path('tipos-juicio/ver/<int:pk>/', TipoJuicioDetailView.as_view(), name='ver_tipo_juicio'),

    # Distrito Judicial
    path('distritos-judiciales/', DistritoJudicialListView.as_view(), name='lista_distritos'),
    path('distritos-judiciales/nuevo/', DistritoJudicialCreateView.as_view(), name='nuevo_distrito'),
    path('distritos-judiciales/editar/<int:pk>/', DistritoJudicialUpdateView.as_view(), name='editar_distrito'),
    path('distritos-judiciales/ver/<int:pk>/', DistritoJudicialDetailView.as_view(), name='ver_distrito'),

    # Tipo juzgado
    #path('tipos-juzgado/', TipoJuzgadoListView.as_view(), name='lista_tipos_juzgado'),
    #path('tipos-juzgado/nuevo/', TipoJuzgadoCreateView.as_view(), name='nuevo_tipo_juzgado'),
    #path('tipos-juzgado/editar/<int:pk>/', TipoJuzgadoUpdateView.as_view(), name='editar_tipo_juzgado'),
    #path('tipos-juzgado/ver/<int:pk>/', TipoJuzgadoDetailView.as_view(), name='ver_tipo_juzgado'),
    #path('tipos-juzgado/eliminar/<int:pk>/', TipoJuzgadoDeleteView.as_view(), name='eliminar_tipo_juzgado'),

    # Region judicial
    path('regiones-judiciales/', RegionJudicialListView.as_view(), name='lista_regiones'),
    path('regiones-judiciales/nuevo/', RegionJudicialCreateView.as_view(), name='nueva_region'),
    path('regiones-judiciales/editar/<int:pk>/', RegionJudicialUpdateView.as_view(), name='editar_region'),
    path('regiones-judiciales/ver/<int:pk>/', RegionJudicialDetailView.as_view(), name='ver_region'),

    # Organo juridiccial
    path('organo-juridiccial/', OrganoJurisdiccionalListView.as_view(), name='lista_organosjurisdiccionales'),
    path('organo-juridiccial/nuevo/', OrganoJurisdiccionalCreateView.as_view(), name='nuevo_organojurisdiccional'),
    path('organo-juridiccial/editar/<int:pk>/', OrganoJurisdiccionalUpdateView.as_view(), name='editar_organojurisdiccional'),

    path('estadisticas/', EstadisticasDashboardView.as_view(), name='dashboard_estadisticas'),

    #Usuarios
    path('usuarios/', UserListView.as_view(), name='lista_usuarios'),
    path('usuario/nuevo/', UserCreateView.as_view(), name='nuevo_usuario'),
    path('usuario/<int:pk>/', UserDetailView.as_view(), name='ver_usuario'),
    path('usuario/<int:pk>/editar/', UserUpdateView.as_view(), name='editar_usuario'),
    path('usuario/<int:pk>/eliminar/', UserDeleteView.as_view(), name='eliminar_usuario'),

]

app_sicpej/apps_sicpej/administracion/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

from django.contrib.auth import get_user_model

User = get_user_model()
    
class Estado(models.Model):
    clave = models.CharField(max_length=10, null=True, blank=True)
    descripcion = models.CharField(max_length=200)

    def __str__(self):
        return '{}'.format(self.descripcion)

class Municipio(models.Model):
    clave = models.CharField(max_length=10, null=True, blank=True)
    descripcion = models.CharField(max_length=250)
    id_estado = models.ForeignKey(Estado, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return '{} - {}'.format(self.id, self.descripcion)

class Localidad(models.Model):
    descripcion = models.CharField(max_length=150)
    id_estado = models.ForeignKey(Estado, on_delete=models.CASCADE, null=True, blank=True)
    id_municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE, null=True, blank=True)
    ambito = models.CharField(max_length=2, null=True, blank=True)

class ArchivoRegional(models.Model):
    ESTATUS = (
        (0, "No activo"),
        (1, "Activo")
    )
    nombre = models.CharField(max_length=255)
    #municipio = models.TextField(null=True, blank=True)
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE,null=True)
    locacion = models.TextField(null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)
    clave = models.CharField(max_length=50,null=True, blank=True)
    nombre_corto = models.CharField(max_length=50,null=True, blank=True)
    rgb_color_identificacion = models.CharField(max_length=15,null=True, blank=True)
    estatus = models.PositiveSmallIntegerField(choices=ESTATUS, default=1)
    # Campos de auditoría
    creado_por = models.ForeignKey(User,  on_delete=models.SET_NULL, null=True, related_name='archivos_regionales_creados')
    actualizado_por = models.ForeignKey( User, on_delete=models.SET_NULL, null=True, related_name='archivos_regionales_actualizados')
    fecha_creacion = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True,null=True, blank=True)
    
    def __str__(self):
        return self.nombre or "Sin nombre"

class TipoJuzgado(models.Model):
    ESTATUS = (
        (0, "No activo"),
        (1, "Activo")
    )

    nombre = models.CharField(max_length=200, unique=True)
    descripcion = models.TextField(blank=True, null=True)
    nota = models.TextField(blank=True, null=True)
    estatus = models.PositiveSmallIntegerField(choices=ESTATUS, default=1)
    
    # Campos de auditoría
    creado_por = models.ForeignKey( User,  on_delete=models.SET_NULL,  null=True,  related_name='tipos_juzgado_creados')
    actualizado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='tipos_juzgado_actualizados')
    fecha_creacion = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True,null=True, blank=True)
    
    class Meta:
        verbose_name = "Tipo juzgado"
        verbose_name_plural = "Tipo juzgado"
        ordering = ['nombre']
    
    def __str__(self):
        return self.nombre
    
class Materia(models.Model):
    ESTATUS = (
        (0, "No activo"),
        (1, "Activo")
    )

    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(blank=True, null=True)
    nota = models.TextField(blank=True, null=True)
    estatus = models.PositiveSmallIntegerField(choices=ESTATUS, default=1)

    # Campos de auditoría
    creado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='materias_creadas')
    actualizado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='materias_actualizadas')
    fecha_creacion = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True,null=True, blank=True)
    
    class Meta:
        verbose_name = "Materia"
        verbose_name_plural = "Materias"
        ordering = ['nombre']
    
    def __str__(self):
        return self.nombre

class DistritoJudicial(models.Model):
    ESTATUS = (
        (0, "No activo"),
        (1, "Activo")
    )

    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(blank=True, null=True)
    locacion = models.CharField(max_length=500, null=True, blank=True)
    direccion = models.CharField(max_length=500, null=True, blank=True)
    nota = models.TextField(blank=True, null=True)
    archivo_regional = models.ForeignKey(ArchivoRegional, on_delete=models.CASCADE,null=True, blank=True)
    materia = models.ForeignKey( Materia, on_delete=models.SET_NULL, null=True, blank=True,related_name='materias')
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE,blank=True, null=True)
    estatus = models.PositiveSmallIntegerField(choices=ESTATUS, default=1)

    # Campos de auditoría
    creado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='distritos_creados')
    actualizado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='distritos_actualizados')
    fecha_creacion = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True,null=True, blank=True)
    
    class Meta:
        verbose_name = "Distrito Judicial"
        verbose_name_plural = "Distritos Judiciales"
        ordering = ['nombre']
    
    def __str__(self):
        return self.nombre
    
class RegionJudicial(models.Model):
    ESTATUS = (
        (0, "No activo"),
        (1, "Activo")
    )

    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(blank=True, null=True)
    nota = models.TextField(blank=True, null=True)
    #archivo_regional = models.ForeignKey(ArchivoRegional, on_delete=models.CASCADE,null=True, blank=True)
    materia = models.ForeignKey( Materia, on_delete=models.SET_NULL, null=True, blank=True,related_name='regiones_judiciales')
    estatus = models.PositiveSmallIntegerField(choices=ESTATUS, default=1)

    # Campos de auditoría
    creado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='regiones_judiciales_creadas')
    actualizado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='regiones_judiciales_actualizadas')
    fecha_creacion = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True,null=True, blank=True)
    
    class Meta:
        verbose_name = "Región judicial"
        verbose_name_plural = "Regiones judijciales"
        ordering = ['nombre']
    
    def __str__(self):
        return self.nombre
 
class Juzgado(models.Model):
    TIPO = (
        (1, "FAMILIAR"),
        (2, "MERCANTIL"),
        (3, "CIVIL"),
        (4, "PENAL"),
        (5, "LABORAL"),
        (6, "MIXTO"),
        (7, "CONCILIACION"),
        (8, "OFICIALIA DE PARTES"),
        (9, "DE PAZ "),
        (13, "FEDERAL"),
        (14, "CONSIGNACIONES Y PAGOS"),
    )

    ESTATUS = (
        (0, "No activo"),
        (1, "Activo")
    )

    nombre = models.CharField(max_length=550)
    nombre_corto = models.CharField(max_length=50,null=True, blank=True)
    descripcion = models.TextField()
    clave_interna = models.CharField(max_length=50,null=True, blank=True)
    locacion = models.CharField(max_length=500, null=True, blank=True)
    direccion = models.CharField(max_length=500, null=True, blank=True)
    municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE)
    archivo_regional = models.ForeignKey(ArchivoRegional, on_delete=models.CASCADE)
    distrito_judicial = models.ForeignKey(DistritoJudicial,on_delete=models.SET_NULL,null=True,blank=True,verbose_name="Distrito Judicial o Región")
    region_judicial = models.ForeignKey(RegionJudicial,on_delete=models.SET_NULL,null=True,blank=True,verbose_name="Región Judicial")
    #RegionJudicial
    #tipo = models.PositiveSmallIntegerField(choices=TIPO, default=1)
    tipo_juzgado = models.ForeignKey(TipoJuzgado, on_delete=models.CASCADE,null=True, blank=True,related_name='juzgados')
    materia = models.ForeignKey( Materia, on_delete=models.SET_NULL, null=True, blank=True,related_name='juzgados')
    estatus = models.PositiveSmallIntegerField(choices=ESTATUS, default=1)
    #created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    
    # Campos de auditoría
    creado_por = models.ForeignKey(User, on_delete=models.SET_NULL,  null=True, related_name='juzgados_creados')
    actualizado_por = models.ForeignKey( User, on_delete=models.SET_NULL, null=True, related_name='juzgados_actualizados')
    fecha_creacion = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True,null=True, blank=True)

    def nombre_en_fecha(self, fecha):
        if not fecha:
            return self.nombre or "Sin nombre"
        
        nombre_historico = self.nombres_historicos.filter(
            fecha_inicio__lte=fecha,
            fecha_fin__gte=fecha
        ).order_by('-fecha_inicio').first()
        
        return nombre_historico.nombre if nombre_historico else self.nombre
    
    def __str__(self):
        return self.nombre or "Sin nombre"

class Instancia(models.Model):
    ESTATUS = (
        (0, "No activo"),
        (1, "Activo")
    )
    
    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(blank=True, null=True)
    nota = models.TextField(blank=True, null=True)
    estatus = models.PositiveSmallIntegerField(choices=ESTATUS, default=1)

    # Campos de auditoría

app_sicpej/apps_sicpej/administracion/templates/organo_jurisdiccional/lista_organojurisdiccionales.html
{% extends 'sicpej/base.html' %}

{% block title %}Lista de organos jurisdiccionales{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-10">
                <h5>Lista de organos jurisdiccionales</h5>
            </div>
            <div class="col-md-2 text-right">
                <a href="{% url 'administracion:nuevo_organojurisdiccional' %}" class="btn btn-primary mt-4">Nuevo organo jurisdiccional</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        
        <div class="table-responsive text-nowrap">
            <table class="table">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Archivo Regional</th>
                        <th>Municipio</th>
                        <th>Materia</th>
                        <th>Estatus</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for organo_jurisdiccional in organos_juridiccionales %}
                    <tr>
                        <td>{{ organo_jurisdiccional.nombre }}</td>
                        <td>{{ organo_jurisdiccional.archivo_regional.nombre }}</td>
                        <td>{{ organo_jurisdiccional.municipio.descripcion }}</td>
                        <td>{{ organo_jurisdiccional.materia|default:"-"  }}</td>
                        <td>
                            {% if organo_jurisdiccional.estatus == 1 %}
                                <span class="badge rounded-pill bg-label-primary me-1">{{ organo_jurisdiccional.get_estatus_display }}</span>
                            {% else %}
                                <span class="badge rounded-pill bg-label-dark me-1">Inactivo</span>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'administracion:editar_organojurisdiccional' organo_jurisdiccional.pk %}" class="btn btn-primary waves-effect waves-light">Editar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        {% if is_paginated %}
            <div class="card-footer">
                <div class="row">
                    <div class="col-md-12 m-5">
                        {% include 'sicpej/partials/paginacion.html' %}
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

app_sicpej/apps_sicpej/administracion/templates/organo_jurisdiccional/organojurisdiccional_form.html
{% extends 'sicpej/base.html' %}

{% block title %}{{ accion }} juzgado{% endblock %}

{% block content %}
<div class="col-md-9 offset-md-1">
  <div class="card">
    <div class="card-header d-flex align-items-center justify-content-between">
      <h5 class="mb-0">{{ titulo }}</h5>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}

        <div class="row mb-4">
        {% for field in form %}
        
              {% if field.name in form.one_column_fields %}
                <div class="col-12 mb-5">
              {% elif field.name in form.two_column_fields %}
                <div class="col-md-6 mb-5">
              {% elif field.name in form.three_column_fields %}
                <div class="col-md-4 mb-5">
              {% elif field.name in form.four_column_fields %}
                <div class="col-md-3 mb-5">
              {% else %}
                <div class="col-12 mb-5">
              {% endif %}
                  <div class="row">
                  
                  {% if field.name in form.two_column_fields %}
                    <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-8">
                  {% else %}
                    <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
                    <div class="col-sm-10">
                  {% endif %}
                  
                    {% if field.name == 'municipio' or field.name == 'archivo_regional' or field.name == 'tipo_juzgado' or field.name == 'materia' or field.name == 'estatus' or field.name == 'instancia' %}
                      <select name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-select {% if field.errors %}is-invalid{% endif %} select2" required>
                        {% for value, label in field.field.choices %}
                          <option value="{{ value }}" {% if value == field.value %}selected{% endif %}>{{ label }}</option>
                        {% endfor %}
                      </select>
                    {% elif field.name == 'region_judicial' or field.name == 'distrito_judicial' %}
                      <select name="{{ field.name }}" id="{{ field.id_for_label }}" class="form-select {% if field.errors %}is-invalid{% endif %} select2">
                        {% for value, label in field.field.choices %}
                          <option value="{{ value }}" {% if value == field.value %}selected{% endif %}>{{ label }}</option>
                        {% endfor %}
                      </select>
                    {% else %}
                      {{ field }}
                    {% endif %}

                    {% if field.help_text %}
                      <div class="form-text">{{ field.help_text }}</div>
                    {% endif %}

                    {% for error in field.errors %}
                      <div class="invalid-feedback d-block">{{ error }}</div>
                    {% endfor %}
                  </div>
                  </div>
              
            
            </div>
        {% endfor %}
        </div>

        <div class="row justify-content-end">
            <div class="col-sm-12 d-flex justify-content-end">
                <button type="submit" class="btn btn-primary waves-effect waves-light me-2">{{ accion }}</button>
                <a href="{% url 'administracion:lista_organosjurisdiccionales' %}" class="btn btn-secondary">Cancelar</a>
            </div>
        </div>

      </form>
    </div>
  </div>
</div>
{% endblock %}